apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: unit-converter

labels:
  - pairs:
      app.kubernetes.io/name: unit-converter
      app.kubernetes.io/component: console-app

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: unit-converter

images:
  - name: unit-converter
    newTag: latest
