name: grey_sdk
description: Grey Multi-Tenant SDK for Dart using gRPC transport.
version: 0.1.0
homepage: https://github.com/grey/grey-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
