apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calcalories-pvc
  labels:
    app: calcalories
    app.kubernetes.io/name: calcalories
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uncomment and specify storageClassName if needed
  # storageClassName: standard
