apiVersion: v1
kind: Service
metadata:
  name: calcalories-service
  labels:
    app: calcalories
    app.kubernetes.io/name: calcalories
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app: calcalories
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
