name = "GreySDK"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Grey Team <team@grey.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
julia = "1.6"
HTTP = "1.0"
JSON3 = "1.0"
StructTypes = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
