# =============================================================================
# Kustomization file for password_checker Kubernetes resources
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: password-checker

namespace: default

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - job.yaml
  - cronjob.yaml

commonLabels:
  app: password-checker

images:
  - name: password-checker
    newName: password-checker
    newTag: "0.1.0"
